import os
from google import genai
from google.genai.errors import APIError

class Translator:
    """
    Gemini API를 사용하여 텍스트를 원하는 언어로 번역하는 클래스입니다.
    """
    def __init__(self, model_name: str = 'gemini-2.5-flash'):
        """
        초기화 시 Gemini API 클라이언트를 설정합니다.
        GOOGLE_API_KEY 환경 변수가 설정되어 있어야 합니다.
        """
        try:
            # 환경 변수에서 API 키를 자동으로 가져옵니다.
            self.client = genai.Client()
            self.model = model_name
        except Exception as e:
            print(f"클라이언트 초기화 오류: {e}")
            print("GOOGLE_API_KEY 환경 변수가 설정되어 있는지 확인하세요.")
            self.client = None
            

    def translate(self, text: str, source_language: str, target_language: str) -> str:
        """
        입력된 텍스트를 원하는 언어로 번역합니다.

        Args:
            text (str): 번역할 자연어 텍스트입니다.
            source_language (str): 입력된 텍스트의 언어입니다 (예: 'Korean', 'English').
            target_language (str): 번역을 진행할 대상 언어입니다 (예: 'English', 'French').

        Returns:
            str: 번역된 텍스트 또는 오류 메시지입니다.
        """
        if not self.client:
            return "번역 서비스를 사용할 수 없습니다. 클라이언트 초기화 오류를 확인하세요."

        # 명확한 번역 지침을 제공하는 프롬프트를 구성합니다.
        prompt = (
            f"다음 조건에 맞추어 {source_language} 텍스트를 {target_language}로 번역하세요. "
            f"## 조건: \n\n"
            f"입력으로 들어간 모든 내용을 빠짐없이 번역하여야 한다.\n"
            f"수식의 경우 '$'문자로 둘러쌓인 mathtext 문법으로 전환하라.\n"
            f"입력에 개행 문자가 있는 경우 출력에도 비슷한 위치에 개행 문자가 추가되어야 한다.\n"
            f"간혹 페이지가 넘어가 문단이 잘리는 경우가 있다. 이러한 경우 문맥을 고려하여 문장 단위에서 적절히 잘라주어야 한다.\n"
            f"문단이 넘어가는 순간은 문단 넘김 문자(\"\n-----\n\") 문자로 구분된다.\n"
            f"문단의 갯수는 문단 넘김문자로 구분되며 **입력 문단의 개수와 출력 문단의 개수는 반드시 동일** 해야한다.\n"
            f"**입력 문단과 출력 문단에서 문단 넘김 문자의 개수는 반드시 동일** 해야한다.\n"
            f"전문 용어(convolution, knowledge distillation, transformer, attention 등)는 번역하지 마라.\n"
            f"반말로 평서문체(보고서체)를 사용해 번역하라..\n"
            f"오직 번역된 텍스트만 응답하라.\n"
            f"텍스트: \"{text}\""
        )
        
        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt
            )
            # 불필요한 공백이나 줄바꿈을 제거하고 번역된 텍스트만 반환합니다.
            return response.text.strip()
        
        except APIError as e:
            return f"Gemini API 오류 발생: {e}"
        except Exception as e:
            return f"예기치 않은 오류 발생: {e}"

# ---

## 사용 예시
if __name__ == "__main__":

    # GOOGLE_API_KEY 환경 변수를 설정해야 합니다.
    # os.environ['GOOGLE_API_KEY'] = 'YOUR_API_KEY' 

    # 'Translator' 클래스의 인스턴스를 생성합니다.
    translator = Translator()

    # 번역할 텍스트 및 언어를 정의합니다.
    korean_text = "To extract high-quality knowledge, previous studies usually increase the size of the teacher model. However, when employing an excessively large teacher model, the performance of the student model may decrease because of the capacity gap. Due to this issue, increasing the size of the teacher model cannot improve the\n-----\n  student model’s performance beyond a certain \n threshold. In other words, there are limitations in the quality of knowledge extracted from the teacher model and transferred to the student model. To address these issues, we propose an Oracle teacher model that extracts high-quality knowledge through the use of reinforced data, generated by XAI."
    source = "English"
    target = "Korean"

    # 번역을 실행합니다.
    translated_text = translator.translate(korean_text, source, target)

    print(f"원본 ({source}): {korean_text}")
    print(f"번역 ({target}): {translated_text}")

    # ---

    ## 클래스 구현 설명

    # 1.  **`__init__(self, model_name)`**:
    #     * `genai.Client()`를 사용하여 **Gemini API 클라이언트**를 초기화합니다. 이 때 `GOOGLE_API_KEY` 환경 변수가 설정되어 있어야 합니다.
    #     * 사용할 모델을 `gemini-2.5-flash`로 기본 설정합니다.

    # 2.  **`translate(self, text, source_language, target_language)`**:
    #     * **프롬프트 엔지니어링**: Gemini 모델에게 번역 역할을 명확히 지시하는 프롬프트를 구성합니다. "오직 번역된 텍스트만 응답"하도록 요청하여 모델의 출력을 단순화합니다.
    #     * **API 호출**: `self.client.models.generate_content` 메서드를 사용하여 Gemini API에 요청을 보냅니다.
    #     * **결과 반환**: 응답에서 번역된 텍스트만 추출하여 반환합니다.

    # 이 비디오는 Gemini Pro API와 Python을 사용하여 실시간 언어 번역기를 구축하는 방법을 보여주므로, 번역 기능 구현에 도움이 됩니다: [Build a Google Gemini Powered Real-Time Language Translator with Python](https://www.youtube.com/watch?v=n1l81Vv6qQI).
    # http://googleusercontent.com/youtube_content/0